name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing.
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  
  
  
  
    



